const videoData = [
  {
    id: '1',
    title: 'Learn React in 15 Minutes',
    thumbnail: 'https://i.ytimg.com/vi/DLX62G4lc44/hqdefault.jpg',
    channelName: 'Code with Nav',
    channelAvatar: 'https://i.pravatar.cc/40?img=1',
    views: 125000,
    uploadedAt: '2 weeks ago',
    duration: '15:23',
  },
  {
    id: '2',
    title: 'JavaScript Full Course for Beginners',
    thumbnail: 'https://i.ytimg.com/vi/PkZNo7MFNFg/hqdefault.jpg',
    channelName: 'FreeCodeCamp',
    channelAvatar: 'https://i.pravatar.cc/40?img=2',
    views: 1125000,
    uploadedAt: '1 month ago',
    duration: '3:32:10',
  },
  {
    id: '3',
    title: 'CSS Grid Tutorial | Build Layouts Easily',
    thumbnail: 'https://i.ytimg.com/vi/jV8B24rSN5o/hqdefault.jpg',
    channelName: 'DesignCourse',
    channelAvatar: 'https://i.pravatar.cc/40?img=3',
    views: 52000,
    uploadedAt: '5 days ago',
    duration: '10:45',
  },
  {
    id: '4',
    title: 'Top 10 VSCode Extensions for Web Devs',
    thumbnail: 'https://i.ytimg.com/vi/fJEbVCrEM7k/hqdefault.jpg',
    channelName: 'TechZone',
    channelAvatar: 'https://i.pravatar.cc/40?img=4',
    views: 189000,
    uploadedAt: '1 week ago',
    duration: '7:19',
  },
  {
    id: '5',
    title: 'Understanding Flexbox in 12 Minutes',
    thumbnail: 'https://i.ytimg.com/vi/fYq5PXgSsbE/hqdefault.jpg',
    channelName: 'The Net Ninja',
    channelAvatar: 'https://i.pravatar.cc/40?img=5',
    views: 67000,
    uploadedAt: '3 days ago',
    duration: '12:06',
  },
  {
    id: '6',
    title: 'How to Make a YouTube Clone with React',
    thumbnail: 'https://i.ytimg.com/vi/UjeXP1lDfLQ/hqdefault.jpg',
    channelName: 'CodeWithHarry',
    channelAvatar: 'https://i.pravatar.cc/40?img=6',
    views: 143000,
    uploadedAt: '4 weeks ago',
    duration: '22:10',
  },
  {
    id: '7',
    title: 'Responsive Navbar with Tailwind CSS',
    thumbnail: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    channelName: 'Tailwind Mastery',
    channelAvatar: 'https://i.pravatar.cc/40?img=7',
    views: 34000,
    uploadedAt: '1 day ago',
    duration: '8:37',
  },
  {
    id: '8',
    title: 'React vs Angular vs Vue — Which to Learn?',
    thumbnail: 'https://i.ytimg.com/vi/6bo3dpR0p9M/hqdefault.jpg',
    channelName: 'Programming Insight',
    channelAvatar: 'https://i.pravatar.cc/40?img=8',
    views: 220000,
    uploadedAt: '2 months ago',
    duration: '18:40',
  },
];

export default videoData;
